<?php

declare(strict_types=1);

namespace Horde\Composer;

class RegistrySnippetFileWriter
{
    /**
     * Undocumented function
     *
     * @param DirectoryTree $tree
     * @param Filesystem $filesystem
     * @param string[] $apps
     * @param ReconfigureOptions $options
     */
    public function __construct(
        private DirectoryTree $tree,
        private Filesystem $filesystem,
        private array $apps,
        private ReconfigureOptions $options = new ReconfigureOptions(),
    ) {
    }

    public function run(): void
    {
        $tree = $this->tree;
        $configDir = $tree->getVarConfigDir();
        $configRegistryDir = $configDir . DIRECTORY_SEPARATOR . 'horde' . DIRECTORY_SEPARATOR . 'registry.d';
        $webDir = $tree->getWebReadableRootDir();
        $webrootUri = $this->options->webroot;

        // Ensure we have the base locations right
        $registry00FilePath = $configRegistryDir . '/00-horde.php';

        // Check if paths have changed (migration detection)
        $needsRegeneration = false;
        if (file_exists($registry00FilePath)) {
            $existingContent = file_get_contents($registry00FilePath);
            // Check if file contains old base directory path
            if (strpos($existingContent, '$deployment_fileroot') !== false
                && strpos($existingContent, $webDir) === false) {
                $needsRegeneration = true;
            }
        }

        if (!file_exists($registry00FilePath) || $needsRegeneration) {
            $registry00FileContent = '<?php' . PHP_EOL
            . '/**' . PHP_EOL
            . ' * AUTOGENERATED ONLY IF ABSENT' . PHP_EOL
            . ' * Edit this file to match your needs' . PHP_EOL
            . ' * To reset from defaults, run `composer horde:reconfigure --force --mode=' . $this->options->mode . '`' . PHP_EOL
            . ' */' . PHP_EOL;
            $registry00FileContent .= sprintf(
                '$deployment_webroot = \'%s\';
$deployment_fileroot = \'%s\';
$app_fileroot = \'%s\';
$app_webroot = \'%s\';
',
                $webrootUri,
                $webDir,
                $webDir . DIRECTORY_SEPARATOR . 'horde',
                '/horde',
            );
            $this->filesystem->filePutContentsIfModified($registry00FilePath, $registry00FileContent);
        }
        $webrootOverrideFilePath = $configRegistryDir . '/03-override-webroots.php';
        $webrootOverrideFileSnippet = '<?php' . PHP_EOL
        . '/**' . PHP_EOL
        . ' * AUTOGENERATED ONLY IF ABSENT' . PHP_EOL
        . ' * If you activate at least one of these lines, please also set a full https URL for the default webroot where the remaining apps and the assets (js, themes, static) are located' . PHP_EOL
        . ' * Run `composer horde:reconfigure --mode=' . $this->options->mode . ' --webroot="https://assets.example.com/"`' . PHP_EOL
        . ' */' . PHP_EOL;

        // Ensure we have a base
        foreach ($this->apps as $app) {
            [$appVendor, $appName] = explode('/', $app);
            $webrootOverrideFileSnippet .= '// Customize ' . $app . ' webroot' . PHP_EOL;
            $webrootOverrideFileSnippet .= "// \$this->applications['$appName']['webroot'] = 'https://$appName.example.com/';" . PHP_EOL;
            $registryAppSnippet = '<?php' . PHP_EOL
            . '/**' . PHP_EOL
            . ' * AUTOGENERATED FILE WILL BE OVERWRITTEN ON EACH' . PHP_EOL
            . ' * composer horde-reconfigure or install/update' . PHP_EOL
            . ' * Override settings in either:' . PHP_EOL
            . ' * - var/config/horde/registry.local.php' . PHP_EOL
            . ' * - var/config/horde/registry.d/ snippets, i.e. 99-custom.php' . PHP_EOL
            . ' * - var/config/horde/registry-sub.domain.org.php' . PHP_EOL
            . ' */' . PHP_EOL;

            $appInVendorDir = $tree->getVendorPackageDir($appVendor, $appName);

            $application = '$this->applications[\'' . $appName . '\']';
            $registryAppSnippet
                .= $application . "['fileroot'] = '$appInVendorDir/';\n"
                . $application . "['templates'] = '$appInVendorDir/templates/';\n"
                . $application . "['webroot'] = '$webrootUri$appName/';\n"
                . $application . "['themesuri'] = '$webrootUri" . "themes/$appName';\n"
                . $application . "['jsuri'] = '$webrootUri". "js/$appName';\n";

            if ($appName == 'horde') {
                $order = '01';
                $registryAppSnippet
                    .= $application . "['staticuri'] = '{$webrootUri}static/';\n"
                    . $application . "['themesfs'] = \$deployment_fileroot . '/themes/horde/';\n"
                    . $application . "['jsfs'] = \$deployment_fileroot . '/js/horde/';\n"
                    . $application . "['staticfs'] = \$deployment_fileroot . '/static';\n";
            } else {
                // A registry snippet should ensure the install dir is known
                $order = '02';
                $registryAppSnippet
                    .= $application . "['themesfs'] = '$webDir/themes/$appName/';\n"
                    . $application . "['jsfs'] = '$webDir/js/$appName/';\n"
                    . "// End of $appName registry snippet\n";
            }

            $registryAppFilename = $configRegistryDir . '/' . $order . '-location-' . $appName . '.php';

            // Some versions of the middleware router require the routes.php file to exist even if empty
            $routesFilePath = $appInVendorDir . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'routes.php';
            if (is_dir(dirname($routesFilePath)) && !file_exists($routesFilePath)) {
                $this->filesystem->filePutContentsIfModified($routesFilePath, '<?php' . PHP_EOL . '// Empty default routes file. Put custom routes into var/config/' . $appName . '/routes.local.php and run composer horde:reconfigure' . PHP_EOL);
            }
            $this->filesystem->filePutContentsIfModified($registryAppFilename, $registryAppSnippet);
        }
        if (!file_exists($webrootOverrideFilePath)) {
            $this->filesystem->filePutContentsIfModified($webrootOverrideFilePath, $webrootOverrideFileSnippet);
        }
    }
}
